### ISSUE TITLE
[katana] Translate `UsdUINodeGraphNodeAPI` attributes to `material.layout` group

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/OpenUSD#1019]
This is a feature request rather than an issue.

It would be great if `usdKatana` translated the node graph "look-and-feel" attributes defined on the `UsdUINodeGraphNodeAPI` schema to the `material.layout` group, which stores graph layout information from the new `NetworkMaterialCreate` context in Katana 3.2. The API schema doesn't provide full coverage of the attribute conventions for the `material.layout` group, but the mapping of the current functionality overlap looks to be:

- `ui:nodegraph:node:pos` -> `material.layout.<node>.position`
- `ui:nodegraph:node:displayColor` -> `material.layout.<node>.color`
- `ui:nodegraph:node:expansionState` -> `material.layout.<node>.viewState`

It may also be worth expanding the attributes on the API schema to support things like comments, parameter page expansion states, and maybe some other stuff.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5672

**Comment by sunyab** [comment]
Closing out old issue related to the retired usdKatana plugin.
