### ISSUE TITLE
[Katana] USD in Katana is not producing reliable instance source location paths

### ISSUE THREAD

**Issue by ainaerco** [PixarAnimationStudios/OpenUSD#1034]
It looks like for USD prim instances are not producing reliable instance source location in Katana for the components with the same name.

So for example if we have multiple sources under section_A/variants m0, m1, m2 etc. and we isolate instance and it's source we may get this error in render log:

[KatanaProcedural] Error: /root/world/geo/town_default/block_036/houses/house_A_0 - Unable to find instance source for '/root/world/geo/Masters/section_A/variants_geo_0look_0texture_default_0_lod_300/m3'.

I reckon this is because usd loads the stage again and master numbers distributed in different order.

The disadvantages of this:

- We can't reliably create new instances because on render they may get another source than intended.
- We can't alter instance sources using nodes in Katana, which contradicts Katana philosophy.
- We can't isolate instances and their sources.

I've tried to load same usd in usdview and it's producing different Master number for each session, but I reckon it's less of a problem for just viewing.

If needed I can attach usd file.

Tested USD versions 19.11 and 19.05.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5695

**Comment by stevelavietes** [comment]
PxrUsdIn's technique for generating the (stable, human-friendly) path for a master is known to have certain corner-case limits. That's where the m0, m1, m2, m3... possibility comes in when it encounters multiple masters which result in the same path (via the existing approach).

Can you provide a representative example file for what's getting you the .../m3 above? Our production setups don't use "as instance and sources" mode -- so the clash handling has been largely speculative on our part. If your case reveals a common pattern that we can extend PxrUsdIn to handle, I'd be interested in doing it.

**Comment by ainaerco** [comment]
Here's my repro case. Included katana scene and usd files.
https://www.dropbox.com/s/qkjk1oea9zv0ar5/reproUsdInstanceOverrides.zip?dl=0
In this example I'm instancing sphere and box. In katana scene I'm assigning red material on sphere, blue - on box. If I render multiple times it may happen that sphere is getting blue material instead of red. That's the simplest representative example I could think of.

Using Katana 3.0v9, PRMan 21.7, USD 19.11.

**Comment by ainaerco** [comment]
Any ideas about this?

**Comment by stevelavietes** [comment]
I was out of the office last week -- sorry for the delay.

The issue here is that PxrUsdIn uses "modelName" and available variant selections in order to build the master path. None of those are present so it falls back on the name "master". As a result, the fallback "master" name is used and multiple masters match that path (creating the "m0", "m1", etc).

We haven't hit this case prior because our instancing (and that of other studios which use this mode of PxrUsdIn) is done for model assets. For it to work without that, we'd need a better fallback behavior in absence of modelName.

**Comment by ainaerco** [comment]
Hi, could you elaborate a bit about modelName? How to provide it, is it used in pulgin (can't see it in the code)? In production we have a case where we have 2 assets with identical variant set and asset names, in database they have different parent. For example we have two assets building1 and building1. But first one belongs to downtown, second - to suburb. Would it make sense to support some sort of masterName for such cases?

**Comment by spiffmon** [comment]
You author and query modelName via the UsdModelAPI
<http://graphics.pixar.com/usd/docs/api/class_usd_model_a_p_i.html>, with
GetAssetName/SetAssetName . As (tersely) documented, this should contain a
unique enough identifier that you can use it (and it alone) to query your
asset database.  So I think in your case, the modelName/assetName would
need to be something like "downtown:building1"

--spiff

**Comment by sunyab** [comment]
Closing out old issue related to the retired usdKatana plugin.
