### ISSUE TITLE
Binaries with Releases

### ISSUE THREAD

**Issue by mohamede1945** [PixarAnimationStudios/OpenUSD#131]
Hello and Happy new year!

Is it possible to add binaries to the GitHub releases? It's not that easy to setup dependencies correctly and compile the project (at least for me).

I'm right now looking for the maya 2017 plugin on mac, can someone help me get it?

**Comment by jtran56** [comment]
Filed as internal issue #141499.

**Comment by Cewein** [comment]
Shouldn't it be possible now with the python file [build_usd.py](https://github.com/PixarAnimationStudios/OpenUSD/blob/release/build_scripts/build_usd.py) and the current azure pipeline ?

**Comment by meshula** [comment]
Happily, @mohamede1945 was originally asking about downloading the maya-usd plugin artifacts, and that's possible now! They are here: https://github.com/Autodesk/maya-usd/releases
