### ISSUE TITLE
Can we eliminate the use of boost shared pointers? (BOOST_SP_USE_STD_ATOMIC problem)

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenUSD#170]
There is a difficult USD configuration issue around the use of boost shared pointers.

This flag 
```
BOOST_SP_USE_STD_ATOMIC
```
exists as a preprocessor directive, and it is impossible to tell if a compiled version of boost was made with it set to 1 or not.

If you are trying to build USD against a supplied version of boost, instead of one built specifically for USD, it's extremely difficult to narrow the issues down to this flag, and then to work out how to set it.

I would request that we don't use boost shared pointers at all, since for the most part the functionality is covered by std or tbb.

**Comment by jtran56** [comment]
Filed as internal issue #143729.

**Comment by waywardmonkeys** [comment]
I have a branch that seems to do this. It is currently, without all of the requisite cleanup, modifying about 170 files.

To avoid repeatedly rebasing this ... is there a good time to submit it as a pull request?

**Comment by meshula** [comment]
I just wanted to check in and say that this is still an issue.

**Comment by nvmkuruc** [comment]
@meshula @jesschimein I think this issue can be closed.
