### ISSUE TITLE
ZDI reported vulnerability

### ISSUE THREAD

**Issue by seangeggie** [PixarAnimationStudios/OpenUSD#3354]
<redacted>

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10277

**Comment by pixar-oss** [comment]
Hi @seangeggie thank you for reporting!  Could you please use the vulnerability reporting mechanism noted [here](https://github.com/PixarAnimationStudios/OpenUSD/blob/dev/SECURITY.md)?  Thank you!
