### ISSUE TITLE
[usdHoudini] New behavior of handling the "Prefix" attribute is inconsistent

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/OpenUSD#464]
### Description of Issue
In the commit "Output transforms at asset scopes on all frames", some code was added that always looks for the prim at "Prefix" (on USD Rop Output) and sets up the transform on that prim. This caused us a bit of a headache.

First of all, the functions used to update the transforms on any primitive run the update code (unless we are using the overlay mode) using the prim's parent, which will be "/" in this case (or invalid). That creates a bunch of warnings, as USD Output tries to setup XForm op order on the root prim.

Secondly, this primitive is not guaranteed to exists at all, when the "path" parameter is used on the ROP output. In that case, the parameter specified by "path" is going to be used to determine the output path for each Houdini primitive, and there are no guarantees that the path will have the "Prefix" as their common ancestor.

I know that there is an assumption: a prim at "Prefix" will exists, but we feel that assumption is too much.

I see a couple of things that we can do about this:
- Make sure the transform export works with root prims.
- Run setting up the transform for the prim at "Prefix" after the prims have been exported, and don't force creating of a new prim if it doesn't exists. Optionally try to find the root prim and set-up the transform on that.
- Append the "Prefix" to the output path, even if the "path" attribute is used to determine the output path.

### Steps to Reproduce
The behaviour can be seen when "Prefix" and "path" attribute is set on USD ROP Output. For reproducing the issue, refer to the description.

### System Information (OS, Hardware)
Independent of OS/Hardware.

### Package Versions
Latest dev.

### Build Flags
Independent of build flags.

**Comment by jtran56** [comment]
Filed as internal issue #159712.

**Comment by nrusch** [comment]
Just wanted to add that this new behavior will cause a hard crash if there are no GT prims to write out.

**Comment by nrusch** [comment]
Sorry, I was mistaken. The crash was being caused by something else. Please disregard my comment above.

**Comment by sunyab** [comment]
Closing old issue -- USD no longer ships with a Houdini plugin in favor of the Solaris tools natively built-in to Houdini.
