### ISSUE TITLE
[usdview] GL fails to render cube with 6M vertices

### ISSUE THREAD

**Issue by AlexSchwank** [PixarAnimationStudios/OpenUSD#516]
### Description of Issue
I've found an odd issue. I've created a simple cube with 6M vertices in Maya and exported it as ABC and USD file. Rendering the cube in usdview only works sometimes.

`usdview 6MCube.usd` using GL :x:
`usdview 6MCube.usd` using Embree :heavy_check_mark:
`usdview 6MCube.abc` using GL :heavy_check_mark:

The error message is:
```
usdview --defaultsettings 6MCube.usd 

Traceback (most recent call last):
  File "/.../usd/0.8.5/.../lib/python/pxr/Usdviewq/stageView.py", line 1617, in paintGL
    self.DrawAxis(viewProjectionMatrix)
  File "/.../usd/0.8.5/.../lib/python/pxr/Usdviewq/stageView.py", line 968, in DrawAxis
    glslProgram = self.GetSimpleGLSLProgram()
  File "/.../usd/0.8.5/.../lib/python/pxr/Usdviewq/stageView.py", line 960, in GetSimpleGLSLProgram
    ["mvpMatrix", "color"])
  File "/.../usd/0.8.5/.../lib/python/pxr/Usdviewq/stageView.py", line 85, in __init__
    self._glMajorVersion = int(GL.glGetString(GL.GL_VERSION)[0])
  File "/.../python_pyopengl/3.1.0/.../lib/python/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/.../python_pyopengl/3.1.0/.../lib/python/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1281,
        description = 'invalid value',
        baseOperation = glGetString,
        cArguments = (GL_VERSION,),
        result = '4.5.0 NVIDIA 375.66'
)
```

**Good news though**, the issue is resolved when using the new crate file format (`USD_WRITE_NEW_USDC_FILES_AS_VERSION=0.7.0`) although I'm surprised by that. How does this make a difference? I assume the stage was loaded successfully with the current crate format since Embree is working and GL can obviously render it (see ABC and new USDC)...

![6MCube.usd](https://user-images.githubusercontent.com/1038475/40733197-fc2f6166-642c-11e8-87db-2af7ede55265.png)

### Steps to Reproduce
1. in Maya, create poly cube, set width, height, depth subdivision to 1000. export as ABC and USD
2. `usdview 6MCube.usd` with GL 
3. `usdview 6MCube.usd` with Embree
4. `usdview 6MCube.abc`

### System Information (OS, Hardware)
centos7

### Package Versions
0.8.5

**Comment by spiffmon** [comment]
That is truly bizarre, Alex!  While it is true that in the jump from crate
0.4.x to 0.7 the datum used to store array size bumped from 32 bits to 64
bits, your arrays were nowhere near the 32 bit int limit.  And can't
imagine how GL and Embree would behave differently since all the code by
which the interact with USD is shared...

--spiff

**Comment by jtran56** [comment]
Filed as internal issue #161323.

**Comment by AlexSchwank** [comment]
I did some digging. As we expected, the file format isn't the issue. Phew. The issue is caused by _subdivisionScheme_ . The new USDC file contains `uniform token subdivisionScheme = "none"` . Removing it or setting it to the default value _catmullClark_ results in the rendering issues.

**Comment by superfunc** [comment]
Nice digging @AlexSchwank

**Comment by tcauchois** [comment]
Clearing out some old bugs; we've tested this internally and haven't been able to reproduce the issue.  Ok to close?

**Comment by AlexSchwank** [comment]
Totally, thanks Tom.
