### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [PixarAnimationStudios/OpenUSD#6]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [GlfUVTextureStorageData](https://github.com/OpenVSP/OpenVSP/blob/73d3e0f2e4326323036a6c7a3f63300882d99f91/src/geom_api/GuiInterface.cpp#L30)
- [HdMeshTopology::SetQuadInfo](https://github.com/PixarAnimationStudios/USD/blob/2eb01f5cd4c2dae4e1ef9912ca27a93083bb6ef4/pxr/imaging/lib/hd/meshTopology.cpp#L198)

**Comment by amooty** [comment]
Filed as internal issue #135159.

**Comment by superfunc** [comment]
Note this code has been cleaned up since and can be closed: https://github.com/PixarAnimationStudios/USD/blob/022f7ef54ff8ce15120f34e61e078c1daf471153/pxr/imaging/lib/hdSt/meshTopology.cpp#L83

**Comment by elfring** [comment]
There are [further update candidates](https://github.com/PixarAnimationStudios/USD/blob/65320d266057ae0a68626217f54a0298ac092799/pxr/imaging/lib/hd/glslProgram.cpp#L49 "Update candidate: Destructor for HdGLSLProgram") to [consider](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDeleteProgram.xhtml "Delete a program object"), aren't there?

**Comment by superfunc** [comment]
Looks like I was wrong; I hadn't realized this was pointing to a more general problem and not those specific callouts, my apologies.

**Comment by elfring** [comment]
I am just curious if all possible improvements were integrated into this software for the reported search pattern.

**Comment by elfring** [comment]
Would you like to [take another look also at any included software libraries](https://github.com/PixarAnimationStudios/USD/blob/022f7ef54ff8ce15120f34e61e078c1daf471153/third_party/houdini/lib/gusd/UT_StaticInit.h#L62 "Update candidate: Constructor for GusdUT_StaticValHolder")?

**Comment by elfring** [comment]
How will the software evolution be continued around [a class like “GlfUVTextureStorageData”](https://github.com/PixarAnimationStudios/USD/blob/11e064f846d15d9d3cf79abe97939a8eb4f26f2e/pxr/imaging/lib/glf/uvTextureStorageData.cpp#L49 "Update candidate: Destructor for GlfUVTextureStorageData")?

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by Cewein** [comment]
This issue is quite old, is it still relevent ? I am willing to do a thorough check if needed.

**Comment by meshula** [comment]
Bug reports with repro's, and PRs with code quality or quality of life improvements are always welcome of course.

I don't think it's useful to keep a general issue open for years as a substitute for an ongoing review process though. OpenUSD is subject to extensive testing, as well as continuous development, so I'd suggest that if you do undertake a check, please open PRs with suggested improvements, or issues with bug reports if it's not clear how to proceed.

**Comment by meshula** [comment]
I'm closing it out, per my explanation above.

**Comment by elfring** [comment]
:crystal_ball: Would you like to share any more information also according to an internal issue like #135159?

**Comment by meshula** [comment]
135159 is our internal tracking number for this github issue. There is no extra information there.

The pattern of checking the glProgram does not impact correctness or performance so it will probably not get attention in a reasonable amount of time. Since you are still interested in this issue would mind perhaps working with @Cewein to create a PR for us to look at, since he has offered to help?
