### ISSUE TITLE
[USD houdini] camera export

### ISSUE THREAD

**Issue by Jewel-A** [PixarAnimationStudios/OpenUSD#601]
Hi, 
I found camera node for import usd camera to houdini, but how to export camera from houdini to usd?
examples was werry helpful, but they are don't explain haw to export camera too.

Thank you)
 

![screenshot](https://user-images.githubusercontent.com/2632698/44576875-594ebc80-a798-11e8-890c-67813286e660.png)

**Comment by spiffmon** [comment]
Hi @Jewel-A ,
    Unfortunately, we have not been able to prioritize disentangling our internal camera ROP from the Pixar-specific code and idioms it contains... and also don't think a specific ROP for cameras is the right way to go; rather, support for exporting cameras and lights should be added to the primary ROP.  Our FX team is under water, though, and we can't make any promises as to when that work might happen.

--spiff

**Comment by Jewel-A** [comment]
thank you for your response)

**Comment by jtran56** [comment]
Filed as internal issue #USD-4709.

**Comment by Jewel-A** [comment]
here is a solution how to export camera from Houdini to USD:

1. File -> Export -> Alembic
2. Select camera to export (example /obj/cam1), set Frame Range and click Export button.
3. Go to the folder with just written Alembic file and convert it to *.usd with `usdcat camera.abc --out camera.usd` in Terminal.
Done

**Comment by sunyab** [comment]
Closing out old issue -- USD no longer ships with a Houdini plugin in favor of the Solaris tools natively built into Houdini.
