### ISSUE TITLE
[Houdini] rightHanded mesh packed prim with vertex attributes render incorrectly in viewport

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/OpenUSD#631]
### Description of Issue
When a USD mesh with rightHanded orientation and a vertex primvar for color, opacity, or normals is rendered as a packed primitive in the Houdini viewport, the vertex attributes are set on the wrong vertices. When the geometry is unpacked to polygons, the attributes are assigned to the correct attributes.

### Steps to Reproduce
1. Open the attached vertex_colored_grid.hip file into Houdini with the Houdini plugins enabled.
2. Notice that as you move the display flag from file1 to unpack1 and back, the geometry changes. File1 is showing the USD packed primitives. Unpack1 is showing the unpacked polygons.

[vertex_colored_grid.zip](https://github.com/PixarAnimationStudios/USD/files/2403076/vertex_colored_grid.zip)

**Comment by jtran56** [comment]
Filed as internal issue #USD-4775.

**Comment by sunyab** [comment]
Closing old issue -- USD no longer ships with a Houdini plugin. (Plus it looks like #632 fixed this anyway but GitHub failed to close the issue automatically).
