### ISSUE TITLE
[usdKatana] Missing call to ConfigureResolverForAsset

### ISSUE THREAD

**Issue by frenchdog** [PixarAnimationStudios/OpenUSD#828]
### Description of Issue
It is not possible to use an Asset Resolver with a custom context allowing a per asset configuration.

### Steps to Reproduce
Load a custom resolver that is resolving asset paths using its custom resolver context.
 Opening an asset "managed" by such resolver won't work since its context is not configured.

### System Information (OS, Hardware)
Linux
### Package Versions
v19.5

**Comment by jilliene** [comment]
Filed as internal issue #USD-5229

**Comment by sunyab** [comment]
Closing out old issue related to the retired usdKatana plugin.
