### ISSUE TITLE
An unconfigured HdxColorizeTask never converges

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/OpenUSD#874]
### Description of Issue
When an HdxTaskController creates an HdxColorizeTask, but the colorize task is not configured with a specific aov buffer, the task will never converge, so the task controller will never converge, so any progressive rendering will continue forever.

### Steps to Reproduce
1. Create an HdxTaskController but with no aov buffer specified through SetViewportRenderOutput.
2. Note that the HdxColorizeTask is create, but with an empty _aovBufferPath, which results in a null _aovBuffer.
3. In the Execute method, the null _aovBuffer results in an early exit which does not set the _converged flag.
4. Any subsequent call to HdxTaskController::IsConverged will return fals because the colorize task can never converge.

This is admittedly not a standard use case, but it is part of our use case. And it makes sense to me that a colorize task that has not been asked to do anything should always be marked as converged, since it by definition has completed all its work.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5374

**Comment by tcauchois** [comment]
Fixed by PR 875.
