### ISSUE TITLE
Issues compiling with Visual Studio 2015 after 2017 is installed

### ISSUE THREAD

**Issue by crispy4004** [PixarAnimationStudios/OpenUSD#976]
Discovered an issue attempting to re-build USD with VS 2015 after installing VS 2017.  Boost fails to install due to a failure to find mt.exe:

`'mt' is not recognized as an internal or external command,

operable program or batch file.`

Looks like the same problem here:

http://boost.2283326.n4.nabble.com/release-build-Errors-compiling-1-68-0-with-VS2015-after-VS2017-td4704080.html

The *Fix* suggests commenting out the following line:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vcvarsqueryregistry.bat
`@if "%WindowsSdkDir%"=="" @call :GetWin10SdkDir`

Making this modification does allow me to call "mt" from the VS 2015 Developer Command Prompt, but for whatever reason it still fails when running the build_script.py

**Comment by jilliene** [comment]
Filed as internal issue #USD-5576

**Comment by sunyab** [comment]
Closing old issue out -- support for Visual Studio 2015 was dropped in the 23.02 release.
